- name: Initialize cookiecutter project
  command: cookiecutter --no-input {{ cookiecutter_project }}
  args:
    creates: "{{ ansible_env.HOME }}/{{ cookiecutter_project_name }}"

- name: Reset ssh connection to make sure that current user has access to docker daemon
  meta: reset_connection

- name: Setup project with docker-compose
  docker_compose:
    project_src: "{{ cookiecutter_project_name }}"
  register: output

- debug:
    var: output
