--- # This file has been copies from https://raw.githubusercontent.com/cookiecutter-flask/cookiecutter-flask/master/%7B%7Bcookiecutter.app_name%7D%7D/docker-compose.yml and edited
version: '3.6'

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: {{cookiecutter.python_version}}
  INSTALL_NODE_VERSION: {{cookiecutter.node_version}}

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - node-modules:/app/node_modules
    - ./dev.db:/tmp/dev.db

services:
  flask-dev:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    image: "{{cookiecutter.app_name}}-development"
    ports:
      - "5000:5000"
      - "2992:2992"
    depends_on: postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/dev
    <<: *default_volumes

  postgres:
    container_name: postgres
    build:
      dockerfile: Dockerfile-postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  flask-prod:
    build:
      context: .
      target: production
      args:
        <<: *build_args
    image: "{{cookiecutter.app_name}}-production"
    ports:
      - "5000:5000"
    depends_on: postgres
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info
      GUNICORN_WORKERS: 4
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/prod
    <<: *default_volumes

  manage:
    build:
      context: .
      target: manage
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
    image: "{{cookiecutter.app_name}}-manage"
    stdin_open: true
    tty: true
    <<: *default_volumes

volumes:
  node-modules:
  static-build:
  dev-db:
